### ISSUE TITLE
[ERROR] Could not find config file: /var/www/html/dummy/docs/.doctor-rst.yaml

### ISSUE THREAD

**Issue by linawolf** [OskarStark/doctor-rst#1120]
I downloaded the project and run it in ddev with php 8. I made no changes to it and installed it with `ddev composer install`

When I am trying to run it as described in the docs with 

```ddev exec bin/doctor-rst analyze dummy/docs --group=@Symfony```

I get the following error:

``` [ERROR] Could not find config file: /var/www/html/dummy/docs/.doctor-rst.yaml```

Even though the file is present in the designated directory.

Any ideas?

**Comment by OskarStark** [comment]
Hi, is this still a thing?

**Comment by linawolf** [comment]
I gave up..

**Comment by OskarStark** [comment]
Spotted while working: https://github.com/OskarStark/doctor-rst/commit/b9d9302a9cdd9381b663f861ceff190fc9e9a514

**Comment by RCheesley** [comment]
Also having this issue!
