### ISSUE TITLE
Detect wrong spacing for RST directives

### ISSUE THREAD

**Issue by javiereguiluz** [OskarStark/doctor-rst#1152]
The idea is to report issues like this, which are minor but hard to see:

<img width="452" alt="wrong-spacing" src="https://user-images.githubusercontent.com/73419/179456600-515bc846-8f4e-4bef-9522-ab8a33e988f8.png">

Source: https://github.com/symfony/symfony-docs/pull/16979/files

**Comment by OskarStark** [comment]
It's an easy one I guess. If you like you can copy one rule and add some tests. I will be back in September to work on it

**Comment by javiereguiluz** [comment]
I won't have time for this, sadly. If anyone wants to take it over, please do it. Thanks 🙏
