### ISSUE TITLE
DOCtor-RST should report a warning if whitelist entry cannot be found anymore

### ISSUE THREAD

**Issue by OskarStark** [OskarStark/doctor-rst#1245]
Follows
* https://github.com/symfony/symfony-docs/pull/17744

WDYT @alamirault

**Comment by alamirault** [comment]
100% agree ! It was also in my mind.

But I think it's not possible without breaking interface for collecting usage

**Comment by OskarStark** [comment]
No need to stay BC here, currently you cannot use your own rules, this is still on my todo list.

We can introduce a `Violation` object in the first place and handle that, in a following PR we can then somehow add the info to the violation, WDYT?

**Comment by OskarStark** [comment]
Oh we already have `Violation` object in place... but maybe it should be used by the rules directly?

**Comment by alamirault** [comment]
I will try it !

Probably add methods for getting matched `regex` and `lines` rules in `ExcludedViolationList`. And add a method in `AnalyzerResult` for getting unusedWhitelistRules and check that in formatters

**Comment by OskarStark** [comment]
Sounds like a plan
