### ISSUE TITLE
Underline (for headlines) length should match

### ISSUE THREAD

**Issue by OskarStark** [OskarStark/doctor-rst#1271]
Not sure about the rule name yet 🤔 

Follows https://github.com/symfony/symfony-docs/pull/17482/files#r1090257160

**Comment by alamirault** [comment]
I make this error everytime, it's a great rule !

https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#sections

Maybe something like `SectionUnderlineAdornmentMustMatch`
