### ISSUE TITLE
False negative `NoPhpOpenTagInCodeBlockPhpDirective` rule when first line is a comment

### ISSUE THREAD

**Issue by MrYamous** [OskarStark/doctor-rst#1343]
From symfony-docs
https://github.com/symfony/symfony-docs/blob/15465df251c19acff319db5304db7c9471be99e2/components/uid.rst?plain=1#LL129-L132C14

If a php block start with a comment before php open tag, this is not reported as a Violation

**Comment by OskarStark** [comment]
good catch, we should ship php comment lines in both rules 👍 

Open for a PR? At least a failing test case? I can then takeover
