### ISSUE TITLE
False positive `NoPhpOpenTagInCodeBlockPhpDirective` rule with `html+php` codeblock

### ISSUE THREAD

**Issue by MrYamous** [OskarStark/doctor-rst#1345]
From symfony-docs
https://github.com/symfony/symfony-docs/blob/15465df251c19acff319db5304db7c9471be99e2/introduction/from_flat_php_to_symfony.rst?plain=1#LL32-L36C90

This snippet is reported as a Violation

I think with codeblock `html+php` this is normal to use php open tag and this block may be skipped from this rule 
What do you htink about it ?

**Comment by OskarStark** [comment]
Fixed in https://github.com/OskarStark/doctor-rst/pull/1348
