### ISSUE TITLE
False positive related to backslashes

### ISSUE THREAD

**Issue by javiereguiluz** [OskarStark/doctor-rst#1361]
See https://github.com/symfony/symfony-docs/actions/runs/4551752543/jobs/8026213276#step:7:10

RST content is:

```
* Exception and error messages must not contain backticks (e.g. 'The \`foo\` option ...'),
```

We need to wrap the `foo` option in single backticks and they are escaped with `\`, so I think that DOCtor-RST shouldn't display any error message.

Thanks.

**Comment by OskarStark** [comment]
Refs
* https://github.com/symfony/symfony-docs/pull/18143

**Comment by OskarStark** [comment]
Fixed by using `.. diff::`
