### ISSUE TITLE
False positive: Please add 4 spaces for every indention

### ISSUE THREAD

**Issue by javiereguiluz** [OskarStark/doctor-rst#1415]
I saw this error recently: https://github.com/EasyCorp/EasyAdminBundle/actions/runs/5039702464

It's about content like this:

```rst
        /**
         * @param string|false|null $label
         */
        public static function new(string $propertyName, $label = null): self
```

The first line `        /**` is indented by 4 + 4 spaces, but the next ones are indented by 4 + 4 + 1 because that's how PHPDoc works. That's why I think this is a false positive.

**Comment by OskarStark** [comment]
I know, this is still a regression since 1.47.0, as on 1.46.0 the error is not present.

cc @staabm

**Comment by staabm** [comment]
I will habe a look later this week

**Comment by OskarStark** [comment]
Thank you, no stress, 1.46.0 runs fine

**Comment by staabm** [comment]
_note to myself_

full reproduction example is here: https://github.com/EasyCorp/EasyAdminBundle/blob/3af388b7a463d8407f3adbc9156308209a6942bf/doc/fields.rst#L659-L662 (switch to code tab)

**Comment by OskarStark** [comment]
@javiereguiluz can you try to use 1.47.1 directly and not latest tag?

**Comment by OskarStark** [comment]
Did it work?

**Comment by staabm** [comment]
is it still an issue with the latest release?

**Comment by OskarStark** [comment]
friendly ping @javiereguiluz

**Comment by javiereguiluz** [comment]
Sorry for my very late reply. I can't see this error message anymore in CI, so let's close this one as fixed. Thank you all!
