### ISSUE TITLE
Ensure :class: :method: :namespace: starts with `Symfony\\`

### ISSUE THREAD

**Issue by alamirault** [OskarStark/doctor-rst#1651]
https://github.com/symfony/symfony-docs/pull/19515/files

All theses class references use `$this->symfonyRepositoryUrl` ('https://github.com/symfony/symfony/blob/{symfonyVersion}/src') as base path, so we should ensure given namespace is symfony

**Comment by OskarStark** [comment]
Great idea, maybe make the prefix configurable for the rule?
