### ISSUE TITLE
Message is broken

### ISSUE THREAD

**Issue by OskarStark** [OskarStark/doctor-rst#1704]
Follows #1271 and #1337

![CleanShot 2024-04-03 at 22 06 24@2x](https://github.com/OskarStark/doctor-rst/assets/995707/9505ea5f-b0b9-4021-9737-aa7f81caa2f9)

@MrYamous @alamirault I tried to solve this issue, but couldn't fix it 👎

**Comment by alamirault** [comment]
Issue was right, I fixed rst file

https://github.com/symfony/symfony-docs/pull/19729/commits/03bdde0fc7ceb9b583f8810afb8f3161be102a0d

We can close this issue IMO

**Comment by OskarStark** [comment]
The issue yes, but check the message:

"Please ensure title ......" it is cut at the end
