### ISSUE TITLE
`NoBrokenRefDirective` false positive

### ISSUE THREAD

**Issue by OskarStark** [OskarStark/doctor-rst#1822]
![CleanShot 2024-08-28 at 11 10 58@2x](https://github.com/user-attachments/assets/af07a4a0-1eef-494b-864d-fa09c29d0c69)

Another one :-D

**Comment by MrYamous** [comment]
So many unlikely cases :/ I'll fix it today

**Comment by OskarStark** [comment]
Yes it happens often to me too :-D
