### ISSUE TITLE
`OrderedUseStatements` false positive

### ISSUE THREAD

**Issue by MrYamous** [OskarStark/doctor-rst#1868]
IIUC there is a false positive with `OrderedUseStatements.php` from [symfony-docs](https://github.com/symfony/symfony-docs/pull/20347/checks)

<img width="681" alt="Capture d’écran 2024-10-28 à 20 48 52" src="https://github.com/user-attachments/assets/b47541fd-688c-46aa-8e40-9c9881df8ff4">

**Comment by OskarStark** [comment]
It added many php files in one block, my usage just collects all use statements of them, it does not know when it's about a new class

**Comment by MrYamous** [comment]
> It added many php files in one block, my usage just collects all use statements of them, it does not know when it's about a new class 

I think this should not be considered as an `use` statement as it's a regular sentence and not a code block, but maybe this is caused by new class ?

**Comment by OskarStark** [comment]
The last one is correct.

There are many classes and therefore many use statements inside this code block. I always report it at the beginning of the code block

**Comment by MrYamous** [comment]
My bad, thanks for explanations. I close.
