### ISSUE TITLE
Wrong configuration-block usage

### ISSUE THREAD

**Issue by javiereguiluz** [OskarStark/doctor-rst#251]
This is a small problem ... but with very visible consequences. It has happened to me some times in the past:

Wrong RST syntax:

```rst
[...] lorem ipsum::

.. configuration-block::

    [...]
```

Correct syntax:

```rst
[...] lorem ipsum:

.. configuration-block::

    [...]
```

So, the check is to see if there are two colons (`::`) before `.. configuration-block::` instead of just one colon.

**Comment by OskarStark** [comment]
Fixed in https://github.com/OskarStark/doctor-rst/pull/816
