### ISSUE TITLE
False positive in AvoidRepetetiveWords rule

### ISSUE THREAD

**Issue by javiereguiluz** [OskarStark/doctor-rst#322]
Original content:

```rst
Methods Added by ByteString
~~~~~~~~~~~~~~~~~~~~~~~~~~~

These methods are only available for ``ByteString`` objects::

    // returns TRUE if the string contents are valid UTF-8 contents
    b('Lorem Ipsum')->isUtf8(); // true
    b("\xc3\x28")->isUtf8();    // false

    // returns the value of the byte stored at the given position
    // ('नमस्ते' bytes = [224, 164, 168, 224, 164, 174, 224, 164, 184,
    //                  224, 165, 141, 224, 164, 164, 224, 165, 135])
    b('नमस्ते')->byteCode(0);  // 224
    b('नमस्ते')->byteCode(17); // 135
```

Reported error:

```
components/string.rst ✘
  358: The word "164," is used more times in a row.
   ->  //                  224, 165, 141, 224, 164, 164, 224, 165, 135])
```

Maybe we can disable this rule for numeric values and leave it only for words that only use letters? Thanks.

**Comment by OskarStark** [comment]
Hi Javier, I spotted this error too, while you were working in the String component docs and had the same idea to skip numeric values 👍🏻

Would you like to provide a PR?

I am able to do it from the 17th on ...

**Comment by OskarStark** [comment]
For now you can edit .doctor-rst.yaml file and add this line to the whitelist. Maybe add a comment and reference to this issue, so that we can remove it when it’s fixed 👍🏻
