### ISSUE TITLE
[RFC] cli tool

### ISSUE THREAD

**Issue by smoench** [OskarStark/doctor-rst#610]
Currently this project using a "full-stack" symfony which results in unnecessary dependencies.
My proposal would be create a real console application without the `FrameworkBundle`.
The console application can be compiled and released as phar-file. Everyone can download it and execute before submitting a PR. While the docker image only shipping the phar-file.

Deptrac can be used as an example https://github.com/sensiolabs-de/deptrac/blob/master/src/Console/Application.php

**Comment by OskarStark** [comment]
Yes thats what I am planing todo, are you willing to provide a PR? I currently have not that much time for this project
