### ISSUE TITLE
Cache clean string of a line

### ISSUE THREAD

**Issue by smoench** [OskarStark/doctor-rst#620]
Currently `RstParser::clean($line)` is being called very often with some costly `substr`'s. What would you think about caching the result of a clean line? This could be done with a class wrapping /  representing a line:

```php
final class Line
{
    private string $raw;
    private string $clean;
    private bool $blank;

    public function __construct(string $line)
    {
        $this->raw = $line;
        $this->clean = RstParser::clean($line);
        $this->blank = '' === $this->clean;
    }

    public function clean(): string
    {
        return $this->clean;
    }

    public function raw(): string
    {
        return $this->raw;
    }

    public function isBlank(): bool
    {
        return $this->blank;
    }
}
```

**Comment by OskarStark** [comment]
Very useful 👍

**Comment by OskarStark** [comment]
We can make the Line value object more powerful by adding helper methods like:

* `matches()` a regex
* `contains()`

**Comment by OskarStark** [comment]
Maybe the indention count could be added too:

`indention(): int`
