### ISSUE TITLE
Only backslashes in namespace and use statements

### ISSUE THREAD

**Issue by OskarStark** [OskarStark/doctor-rst#718]
Idea is based on https://github.com/symfony/symfony-docs/pull/13918

**Comment by ToluAkin** [comment]
@OskarStark Can i pick this up to work on?

**Comment by OskarStark** [comment]
Sure, thank you 😊

**Comment by ToluAkin** [comment]
@OskarStark I could not find a forward slash used with namespace and use in the php files of this project.
