### ISSUE TITLE
Support RST comments?

### ISSUE THREAD

**Issue by javiereguiluz** [OskarStark/doctor-rst#794]
In RST, two leading dots in a line means "a comment". I used that for example at the bottom of this file: https://raw.githubusercontent.com/EasyCorp/EasyAdminBundle/master/doc/actions.rst to comment an entire doc section.

However, DOCtor-RST treats it as an error instead of a block comment: https://github.com/EasyCorp/EasyAdminBundle/actions/runs/334548259

**Comment by OskarStark** [comment]
That makes sense, could you please add a PR with a failing testcase for the rule which reports the error? That would help a lot!
Maybe @smoench can support us here, too

**Comment by javiereguiluz** [comment]
Closing as "won't fix" because we now support comments in the RST parser, so things are fine. Thanks.
