### ISSUE TITLE
Improve blank lines detection

### ISSUE THREAD

**Issue by apfelbox** [OskarStark/doctor-rst#812]
Hi,

thanks for your great tool!

One suggestion: improving the blank lines detection would be great, so that the following lines don't report the same error with ``$count - 1``:

![2020-11-13 at 10 13](https://user-images.githubusercontent.com/1032411/99052666-0b047e80-2599-11eb-953d-1424a4338d2a.png)

**Comment by OskarStark** [comment]
This makes sense 👍

**Comment by OskarStark** [comment]
@smoench any idea how we can tackle this?

**Comment by smoench** [comment]
maybe #813 is a solution
