### ISSUE TITLE
Rules should not return `?string`, but a `Violation` object

### ISSUE THREAD

**Issue by OskarStark** [OskarStark/doctor-rst#827]

**Comment by AlessandroMinoccheri** [comment]
I was checking this issue and I was thinking about the object `Violation` with his named constructor:

```
public static function from(string $message, string $filename, int $lineno, string $rawLine): self
    {
        return new self($message, $filename, $lineno, $rawLine);
    }
```

In `Rule` classes there isn't the filename, so we have some ways:
* pass the filename to the Rule (I don't like so much it)
* leave the filename empty and we will add it into the `Analyzer` (not so correct to create the Violation without the filename, in my opinion, you have an inconsistent object)

What do you think @OskarStark?
Do you see a clean way to deal with this issue?

**Comment by OskarStark** [comment]
Hi, I am not sure but this project doesn't has a BC promise 
, so we can change everything we want.

What would then be your idea?

**Comment by AlessandroMinoccheri** [comment]
My suggestion would be to pass the filename to the function `check` so we can return a Violation object. 

From this:
```
public function check(Lines $lines, int $number): ?string;
```
To this

```
public function check(Lines $lines, int $number, string $filename): ViolationInterface;
```

What do you think?

**Comment by OskarStark** [comment]
I like the idea

**Comment by alamirault** [comment]
Great ! It will allow setting violation on specific lines and not only on block directive.

However ` $line->raw()->trim()->toString()` must be done in every Rule.

https://github.com/OskarStark/doctor-rst/blob/06fb5cff23bcfdc8157f30b506354da0d8208190/src/Analyzer/RstAnalyzer.php#L110-L119

We can maybe change Violation signature and allow `Line`

`public static function from(string $message, string $filename, int $lineno, string|Line $rawLine): self`

@AlessandroMinoccheri Do you want to work on this feature?

**Comment by AlessandroMinoccheri** [comment]
I can work on it, but I prefer to split the problem:
- Returning a Violation
- Change the Violation signature as you suggest
